const LANGUAGE_CODES: [&'static str; 184] = [
    "aa", "ab", "ae", "af", "ak", "am", "an", "ar", "as", "av", "ay", "az",
    "ba", "be", "bg", "bh", "bi", "bm", "bn", "bo", "br", "bs", "ca", "ce",
    "ch", "co", "cr", "cs", "cu", "cv", "cy", "da", "de", "dv", "dz", "ee",
    "el", "en", "eo", "es", "et", "eu", "fa", "ff", "fi", "fj", "fo", "fr",
    "fy", "ga", "gd", "gl", "gn", "gu", "gv", "ha", "he", "hi", "ho", "hr",
    "ht", "hu", "hy", "hz", "ia", "id", "ie", "ig", "ii", "ik", "io", "is",
    "it", "iu", "ja", "jv", "ka", "kg", "ki", "kj", "kk", "kl", "km", "kn",
    "ko", "kr", "ks", "ku", "kv", "kw", "ky", "la", "lb", "lg", "li", "ln",
    "lo", "lt", "lu", "lv", "mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms",
    "mt", "my", "na", "nb", "nd", "ne", "ng", "nl", "nn", "no", "nr", "nv",
    "ny", "oc", "oj", "om", "or", "os", "pa", "pi", "pl", "ps", "pt", "qu",
    "rm", "rn", "ro", "ru", "rw", "sa", "sc", "sd", "se", "sg", "si", "sk",
    "sl", "sm", "sn", "so", "sq", "sr", "ss", "st", "su", "sv", "sw", "ta",
    "te", "tg", "th", "ti", "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw",
    "ty", "ug", "uk", "ur", "uz", "ve", "vi", "vo", "wa", "wo", "xh", "yi",
    "yo", "za", "zh", "zu"
];

pub fn is_valid_language_code(lang: &str) -> bool {
    LANGUAGE_CODES.into_iter()
                  .position(|l| *l == lang)
                  .is_some()
}

pub enum Language {
    Afar,
    Abkhaz,
    Avestan,
    Afrikaans,
    Akan,
    Amharic,
    Aragonese,
    Arabic,
    Assamese,
    Avaric,
    Aymara,
    Azerbaijani,
    Bashkir,
    Belarusian,
    Bulgarian,
    Bihari,
    Bislama,
    Bambara,
    Bengali,
    TibetanStandard,
    Breton,
    Bosnian,
    Catalan,
    Chechen,
    Chamorro,
    Corsican,
    Cree,
    Czech,
    OldChurchSlavonic,
    Chuvash,
    Welsh,
    Danish,
    German,
    Divehi,
    Dzongkha,
    Ewe,
    Greek,
    English,
    Esperanto,
    Spanish,
    Estonian,
    Basque,
    Persian,
    Fula,
    Finnish,
    Fijian,
    Faroese,
    French,
    WesternFrisian,
    Irish,
    ScottishGaelic,
    Galician,
    Guarani,
    Gujarati,
    Manx,
    Hausa,
    Hebrew,
    Hindi,
    HiriMotu,
    Croatian,
    Haitian,
    Hungarian,
    Armenian,
    Herero,
    Interlingua,
    Indonesian,
    Interlingue,
    Igbo,
    Nuosu,
    Inupiaq,
    Ido,
    Icelandic,
    Italian,
    Inuktitut,
    Japanese,
    Javanese,
    Georgian,
    Kongo,
    Kikuyu,
    Kwanyama,
    Kazakh,
    Kalaallisut,
    Khmer,
    Kannada,
    Korean,
    Kanuri,
    Kashmiri,
    Kurdish,
    Komi,
    Cornish,
    Kyrgyz,
    Latin,
    Luxembourgish,
    Ganda,
    Limburgish,
    Lingala,
    Lao,
    Lithuanian,
    LubaKatanga,
    Latvian,
    Malagasy,
    Marshallese,
    Maori,
    Macedonian,
    Malayalam,
    Mongolian,
    Marathi,
    Malay,
    Maltese,
    Burmese,
    Nauruan,
    NorwegianBokmal,
    NorthernNdebele,
    Nepali,
    Ndonga,
    Dutch,
    NorwegianNynorsk,
    Norwegian,
    SouthernNdebele,
    Navajo,
    Chichewa,
    Occitan,
    Ojibwe,
    Oromo,
    Oriya,
    Ossetian,
    EasternPunjabi,
    Pali,
    Polish,
    Pashto,
    Portuguese,
    Quechua,
    Romansh,
    Kirundi,
    Romanian,
    Russian,
    Kinyarwanda,
    Sanskrit,
    Sardinian,
    Sindhi,
    NorthernSami,
    Sango,
    Sinhalese,
    Slovak,
    Slovene,
    Samoan,
    Shona,
    Somali,
    Albanian,
    Serbian,
    Swati,
    SouthernSotho,
    Sundanese,
    Swedish,
    Swahili,
    Tamil,
    Telugu,
    Tajik,
    Thai,
    Tigrinya,
    Turkmen,
    Tagalog,
    Tswana,
    Tonga,
    Turkish,
    Tsonga,
    Tatar,
    Twi,
    Tahitian,
    Uyghur,
    Ukrainian,
    Urdu,
    Uzbek,
    Venda,
    Vietnamese,
    Volapuk,
    Walloon,
    Wolof,
    Xhosa,
    Yiddish,
    Yoruba,
    Zhuang,
    Chinese,
    Zulu
}

impl Language {
    fn from_str(code: &str) -> Result<Language, String> {
        match code {
            "aa" => Ok(Language::Afar),
            "ab" => Ok(Language::Abkhaz),
            "ae" => Ok(Language::Avestan),
            "af" => Ok(Language::Afrikaans),
            "ak" => Ok(Language::Akan),
            "am" => Ok(Language::Amharic),
            "an" => Ok(Language::Aragonese),
            "ar" => Ok(Language::Arabic),
            "as" => Ok(Language::Assamese),
            "av" => Ok(Language::Avaric),
            "ay" => Ok(Language::Aymara),
            "az" => Ok(Language::Azerbaijani),
            "ba" => Ok(Language::Bashkir),
            "be" => Ok(Language::Belarusian),
            "bg" => Ok(Language::Bulgarian),
            "bh" => Ok(Language::Bihari),
            "bi" => Ok(Language::Bislama),
            "bm" => Ok(Language::Bambara),
            "bn" => Ok(Language::Bengali),
            "bo" => Ok(Language::TibetanStandard),
            "br" => Ok(Language::Breton),
            "bs" => Ok(Language::Bosnian),
            "ca" => Ok(Language::Catalan),
            "ce" => Ok(Language::Chechen),
            "ch" => Ok(Language::Chamorro),
            "co" => Ok(Language::Corsican),
            "cr" => Ok(Language::Cree),
            "cs" => Ok(Language::Czech),
            "cu" => Ok(Language::OldChurchSlavonic),
            "cv" => Ok(Language::Chuvash),
            "cy" => Ok(Language::Welsh),
            "da" => Ok(Language::Danish),
            "de" => Ok(Language::German),
            "dv" => Ok(Language::Divehi),
            "dz" => Ok(Language::Dzongkha),
            "ee" => Ok(Language::Ewe),
            "el" => Ok(Language::Greek),
            "en" => Ok(Language::English),
            "eo" => Ok(Language::Esperanto),
            "es" => Ok(Language::Spanish),
            "et" => Ok(Language::Estonian),
            "eu" => Ok(Language::Basque),
            "fa" => Ok(Language::Persian),
            "ff" => Ok(Language::Fula),
            "fi" => Ok(Language::Finnish),
            "fj" => Ok(Language::Fijian),
            "fo" => Ok(Language::Faroese),
            "fr" => Ok(Language::French),
            "fy" => Ok(Language::WesternFrisian),
            "ga" => Ok(Language::Irish),
            "gd" => Ok(Language::ScottishGaelic),
            "gl" => Ok(Language::Galician),
            "gn" => Ok(Language::Guarani),
            "gu" => Ok(Language::Gujarati),
            "gv" => Ok(Language::Manx),
            "ha" => Ok(Language::Hausa),
            "he" => Ok(Language::Hebrew),
            "hi" => Ok(Language::Hindi),
            "ho" => Ok(Language::HiriMotu),
            "hr" => Ok(Language::Croatian),
            "ht" => Ok(Language::Haitian),
            "hu" => Ok(Language::Hungarian),
            "hy" => Ok(Language::Armenian),
            "hz" => Ok(Language::Herero),
            "ia" => Ok(Language::Interlingua),
            "id" => Ok(Language::Indonesian),
            "ie" => Ok(Language::Interlingue),
            "ig" => Ok(Language::Igbo),
            "ii" => Ok(Language::Nuosu),
            "ik" => Ok(Language::Inupiaq),
            "io" => Ok(Language::Ido),
            "is" => Ok(Language::Icelandic),
            "it" => Ok(Language::Italian),
            "iu" => Ok(Language::Inuktitut),
            "ja" => Ok(Language::Japanese),
            "jv" => Ok(Language::Javanese),
            "ka" => Ok(Language::Georgian),
            "kg" => Ok(Language::Kongo),
            "ki" => Ok(Language::Kikuyu),
            "kj" => Ok(Language::Kwanyama),
            "kk" => Ok(Language::Kazakh),
            "kl" => Ok(Language::Kalaallisut),
            "km" => Ok(Language::Khmer),
            "kn" => Ok(Language::Kannada),
            "ko" => Ok(Language::Korean),
            "kr" => Ok(Language::Kanuri),
            "ks" => Ok(Language::Kashmiri),
            "ku" => Ok(Language::Kurdish),
            "kv" => Ok(Language::Komi),
            "kw" => Ok(Language::Cornish),
            "ky" => Ok(Language::Kyrgyz),
            "la" => Ok(Language::Latin),
            "lb" => Ok(Language::Luxembourgish),
            "lg" => Ok(Language::Ganda),
            "li" => Ok(Language::Limburgish),
            "ln" => Ok(Language::Lingala),
            "lo" => Ok(Language::Lao),
            "lt" => Ok(Language::Lithuanian),
            "lu" => Ok(Language::LubaKatanga),
            "lv" => Ok(Language::Latvian),
            "mg" => Ok(Language::Malagasy),
            "mh" => Ok(Language::Marshallese),
            "mi" => Ok(Language::Maori),
            "mk" => Ok(Language::Macedonian),
            "ml" => Ok(Language::Malayalam),
            "mn" => Ok(Language::Mongolian),
            "mr" => Ok(Language::Marathi),
            "ms" => Ok(Language::Malay),
            "mt" => Ok(Language::Maltese),
            "my" => Ok(Language::Burmese),
            "na" => Ok(Language::Nauruan),
            "nb" => Ok(Language::NorwegianBokmal),
            "nd" => Ok(Language::NorthernNdebele),
            "ne" => Ok(Language::Nepali),
            "ng" => Ok(Language::Ndonga),
            "nl" => Ok(Language::Dutch),
            "nn" => Ok(Language::NorwegianNynorsk),
            "no" => Ok(Language::Norwegian),
            "nr" => Ok(Language::SouthernNdebele),
            "nv" => Ok(Language::Navajo),
            "ny" => Ok(Language::Chichewa),
            "oc" => Ok(Language::Occitan),
            "oj" => Ok(Language::Ojibwe),
            "om" => Ok(Language::Oromo),
            "or" => Ok(Language::Oriya),
            "os" => Ok(Language::Ossetian),
            "pa" => Ok(Language::EasternPunjabi),
            "pi" => Ok(Language::Pali),
            "pl" => Ok(Language::Polish),
            "ps" => Ok(Language::Pashto),
            "pt" => Ok(Language::Portuguese),
            "qu" => Ok(Language::Quechua),
            "rm" => Ok(Language::Romansh),
            "rn" => Ok(Language::Kirundi),
            "ro" => Ok(Language::Romanian),
            "ru" => Ok(Language::Russian),
            "rw" => Ok(Language::Kinyarwanda),
            "sa" => Ok(Language::Sanskrit),
            "sc" => Ok(Language::Sardinian),
            "sd" => Ok(Language::Sindhi),
            "se" => Ok(Language::NorthernSami),
            "sg" => Ok(Language::Sango),
            "si" => Ok(Language::Sinhalese),
            "sk" => Ok(Language::Slovak),
            "sl" => Ok(Language::Slovene),
            "sm" => Ok(Language::Samoan),
            "sn" => Ok(Language::Shona),
            "so" => Ok(Language::Somali),
            "sq" => Ok(Language::Albanian),
            "sr" => Ok(Language::Serbian),
            "ss" => Ok(Language::Swati),
            "st" => Ok(Language::SouthernSotho),
            "su" => Ok(Language::Sundanese),
            "sv" => Ok(Language::Swedish),
            "sw" => Ok(Language::Swahili),
            "ta" => Ok(Language::Tamil),
            "te" => Ok(Language::Telugu),
            "tg" => Ok(Language::Tajik),
            "th" => Ok(Language::Thai),
            "ti" => Ok(Language::Tigrinya),
            "tk" => Ok(Language::Turkmen),
            "tl" => Ok(Language::Tagalog),
            "tn" => Ok(Language::Tswana),
            "to" => Ok(Language::Tonga),
            "tr" => Ok(Language::Turkish),
            "ts" => Ok(Language::Tsonga),
            "tt" => Ok(Language::Tatar),
            "tw" => Ok(Language::Twi),
            "ty" => Ok(Language::Tahitian),
            "ug" => Ok(Language::Uyghur),
            "uk" => Ok(Language::Ukrainian),
            "ur" => Ok(Language::Urdu),
            "uz" => Ok(Language::Uzbek),
            "ve" => Ok(Language::Venda),
            "vi" => Ok(Language::Vietnamese),
            "vo" => Ok(Language::Volapuk),
            "wa" => Ok(Language::Walloon),
            "wo" => Ok(Language::Wolof),
            "xh" => Ok(Language::Xhosa),
            "yi" => Ok(Language::Yiddish),
            "yo" => Ok(Language::Yoruba),
            "za" => Ok(Language::Zhuang),
            "zh" => Ok(Language::Chinese),
            "zu" => Ok(Language::Zulu),
            unknown => Err(format!("Invalid language \"{}\".", unknown)),
        }
    }
}

#[test]
fn str_to_language() {
    assert!(Language::from_str("aa").is_ok());
}